"""
Fetches all NVIDIA NIM models, tests each one with a real request,
and generates models.py with ONLY the working ones (200 OK).

Usage:
    python fetch_nvidia_models.py

Output:
    - Prints working models
    - Saves nvidia_models.json
    - Saves nvidia_working_models.py (ready to paste into models.py)
"""

import os
import json
import time
from openai import OpenAI
from ..config import Settings

# ── config ────────────────────────────────────────────────────────────────────
NVIDIA_API_KEY = Settings.NVIDIA_API_KEY  # os.getenv("NVIDIA_API_KEY", "")

if not NVIDIA_API_KEY:
    raise ValueError(
        "Set NVIDIA_API_KEY env var first:\n  export NVIDIA_API_KEY=nvapi-xxx"
    )

TEST_PROMPT = "Reply with only the word: OK"  # minimal prompt to save tokens
REQUEST_DELAY = 1.5  # seconds between requests (stay under 40 RPM)
SKIP_KEYWORDS = [  # non-chat model types to skip
    "embed",
    "rerank",
    "whisper",
    "tts",
    "asr",
    "vision-only",
    "ocr",
    "detection",
    "bionemo",
    "translate",
    "riva",
]

# ── client ────────────────────────────────────────────────────────────────────
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=NVIDIA_API_KEY,
)

# ── step 1: list all models ───────────────────────────────────────────────────
print("Fetching model list from NVIDIA NIM...\n")
all_models = client.models.list()

candidates = []
for m in all_models.data:
    model_id = m.id
    if any(kw in model_id.lower() for kw in SKIP_KEYWORDS):
        continue
    candidates.append(model_id)

candidates.sort()
print(f"Found {len(candidates)} candidate chat/LLM models.")
print("Testing each with a real request — this will take a few minutes...\n")

# ── step 2: test each model ───────────────────────────────────────────────────
working = []
failed = []

for i, model_id in enumerate(candidates, 1):
    print(f"[{i:>3}/{len(candidates)}] Testing: {model_id} ... ", end="", flush=True)
    try:
        response = client.chat.completions.create(
            model=model_id,
            messages=[{"role": "user", "content": TEST_PROMPT}],
            max_tokens=10,
            timeout=5,
        )
        reply = response.choices[0].message.content.strip()
        print(f"OK  -> '{reply}'")
        working.append(model_id)

    except Exception as e:
        err = str(e)
        if "404" in err:
            reason = "404 Not Found"
        elif "429" in err:
            reason = "429 Rate Limited"
        elif "401" in err:
            reason = "401 Unauthorized"
        elif "timeout" in err.lower():
            reason = "Timeout"
        else:
            reason = err[:60]
        print(f"FAIL ({reason})")
        failed.append({"model": model_id, "reason": reason})

    time.sleep(REQUEST_DELAY)

# ── step 3: report ────────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"Working models : {len(working)}")
print(f"Failed models  : {len(failed)}")
print(f"{'='*60}\n")

# ── step 4: save JSON ─────────────────────────────────────────────────────────
output_json = {
    "working": {m: {"provider": "nvidia", "max_tokens": 32000} for m in working},
    "failed": failed,
}
with open("nvidia_models.json", "w") as f:
    json.dump(output_json, f, indent=4)
print("Saved: nvidia_models.json\n")

# ── step 5: generate models.py snippet ───────────────────────────────────────
py_lines = [
    "# NVIDIA NIM models — tested and verified working\n",
    "# Auto-generated by fetch_nvidia_models.py\n",
    "# Re-run to refresh if models change.\n\n",
]

for model_id in working:
    py_lines.append(f'    "{model_id}": {{\n')
    py_lines.append(f'        "provider": "nvidia",\n')
    py_lines.append(f'        "max_tokens": 32000,\n')
    py_lines.append(f"    }},\n")

with open("nvidia_working_models.py", "w") as f:
    f.writelines(py_lines)

print("Saved: nvidia_working_models.py  <- paste this into your MODELS dict\n")

# ── step 6: print working list ────────────────────────────────────────────────
print("Working models:\n")
for m in working:
    print(f"  {m}")
